# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: __Experimental

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_maven:
    if: ${{ github.repository == 'atlasmap/atlasmap' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        java: [ '21' ]
    name: Java ${{ matrix.Java }} build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java versions
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      id: setup_chrome

    - name: Cache Maven repo
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build from root with Maven
      continue-on-error: true
      run: mvn --batch-mode -Pcoverage -Dwebdriver.chrome.driver=${{ steps.setup_chrome.outputs.chromedriver-path }} clean install
    - name: Build lib with Maven
      continue-on-error: true
      working-directory: lib
      run: mvn --batch-mode clean install
    - name: Build docs
      continue-on-error: true
      working-directory: docs
      run: mvn -Phtml,pdf package
    - name: Build aggregated javadoc
      continue-on-error: true
      working-directory: docs
      run: mvn -f pom-javadoc.xml  -Dfailonerror=true -pl \!io.atlasmap:atlasmap-lib-all javadoc:aggregate
