# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Checked

on:
  push:
    branches: [ test-action ]
  pull_request:
    branches: [ main ]

jobs:
  build_maven:
#    if: ${{ github.repository == 'atlasmap/atlasmap' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        os: [ubuntu-latest, macos-13, windows-2022]
    name: ${{ matrix.os }}/Java${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java versions
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      id: setup_chrome
    - name: Cache Maven repo
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build from root with Maven
      run: mvn --batch-mode -Pcoverage "-Dwebdriver.chrome.driver=${{ steps.setup_chrome.outputs.chromedriver-path }}" clean install
    - name: Build lib with Maven
      working-directory: lib
      run: mvn --batch-mode clean install
    - name: Build docs
      if: ${{ runner.os == 'Linux' }}
      working-directory: docs
      run: mvn "-Phtml,pdf" package
    - name: Build aggregated javadoc
      if: ${{ runner.os == 'Linux' }}
      working-directory: docs
      run: mvn -f pom-javadoc.xml -Dfailonerror=true -pl \!io.atlasmap:atlasmap-lib-all javadoc:aggregate
  chromatic:
    needs: build_maven
    if: |
#      github.repository == 'atlasmap/atlasmap'
#      && github.actor != 'dependabot[bot]'
#      && github.actor != 'dependabot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: marceloprado/has-changed-path@v1
        id: changed-ui
        with:
          paths: ui
      - name: Install dependencies
        if: steps.changed-ui.outputs.changed == 'true'
        run: yarn install
        working-directory: ui
      - name: build @atlasmap/core
        if: steps.changed-ui.outputs.changed == 'true'
        run: yarn build:module
        working-directory: ui/packages/atlasmap-core
      - name: prebuild
        if: steps.changed-ui.outputs.changed == 'true'
        run: yarn prebuild
        working-directory: ui/packages/atlasmap
      - name: Publish to Chromatic
        if: steps.changed-ui.outputs.changed == 'true'
        uses: chromaui/action@v11
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: adaaa25c3df8
          workingDir: ui/packages/atlasmap
          buildScriptName: build:storybook
